version: "3.9"
services:
  server:
    build: .
    container_name: flask_app
    command: gunicorn -w 4 -b 0.0.0.0:5000 hello:app
    environment:
      - FLASK_APP=hello.py
    ports:
      - 5000:5000
